prometheus:
  thanosService:
    enabled: true
  prometheusSpec:
    thanos:
      objectStorageConfig:
        existingSecret:
          name: thanos-secret-config
          key: thanos_persistent_store_secret
      
prometheusOperator:
  thanosImage:
    registry: quay.io
    repository: thanos/thanos
    tag: v0.36.1