prometheus:
  prometheusSpec:
    disableCompaction: true
    storageSpec:
    thanos:
      image: quay.io/thanos/thanos:v0.28.1
      objectStorageConfig:
        existingSecret:
          name: thanos-secret-config
          key: thanos.yaml
  thanosService:
    enabled: true