apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq-cluster
  namespace: observability-metrics #${observability_metrics_namespace}
spec:
  dependsOn:
    - name: observability-metrics-base
  interval: 5m
  path: "./overlay-metrics"
  prune: true
  sourceRef:
    kind: GitRepository
    name: observability-metrics
    namespace: observability-metrics

patches:
  - target:
      version: v1
      kind: Deployment
      name: observability-metrics-kube-state-metrics
      namespace: observability-metrics
    path: kube-state-custom-metrics.yaml
  # - target:
  #     group: v1
  #     version: v1
  #     kind: ServiceAccount
  #     name: observability-metrics-kube-state-metrics
  #     namespace: observability-metrics
  #   patch: |-
  #     apiVersion: v1
  #     kind: ServiceAccount
  #     metadata:
  #       name: observability-metrics-kube-state-metrics
  #       namespace: observability-metrics
  #       annotations:
  #         patched-by: flux




#   apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: rabbitmq-cluster
#   namespace: rabbitmq
# spec:
#   dependsOn:
#     - name: rabbitmq-base
#   interval: 5m
#   path: "./rabbitmq-cluster/custom"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: rabbitmq
#     namespace: rabbitmq