apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability-metrics-base
  namespace: observability-metrics
spec:
  interval: 5m
  path: "./base-service"
  prune: true
  sourceRef:
    kind: GitRepository
    name: observability-metrics
    namespace: observability-metrics