apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: observability-metrics
  namespace: observability-metrics #${observability_metrics_namespace}
  #annotations:
    #xlscsde.nhs.uk/flux-branch: main #${observability-metrics}
spec:
  #targetNamespace: observability-metrics #${observability_metrics_namespace}
  releaseName: observability-metrics
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.8.0" #${observability_metrics_chart_version}
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: observability-metrics #${observability_metrics_namespace} 
  interval: 10s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --metric-labels-allowlist=pods=[*]
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: --custom-resource-state-config
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: |
                  Kind: CustomResourceStateMetrics
                  spec:
                    resources:
                      - groupVersionKind:
                          group: xlscsde.nhs.uk
                          version: "v1"
                          kind: AnalyticsWorkspace
                        metricNamePrefix: lscsde_workspace
                        metrics:
                          - name: "info"
                            help: "AnalyticsWorkspace information"
                            each:
                              type: Info
                              info:
                                labelsFromPath:
                                  workspace: [metadata, name]
                      - groupVersionKind:
                          group: xlscsde.nhs.uk
                          version: "v1"
                          kind: AnalyticsWorkspaceBinding
                        metricNamePrefix: lscsde_workspace_binding
                        metrics:
                          - name: "info"
                            help: "AnalyticsWorkspaceBinding information"
                            each:
                              type: Info
                              info:
                                labelsFromPath:
                                  expires: [spec, expires]
                                  username: [spec, username]
                                  workspace: [spec, workspace]
            target:
              kind: Deployment
              name: observability-metrics-kube-state-metrics
              namespace: observability-metrics