apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: thanos-secret-config
  annotations:
    xlscsde.nhs.uk/secretUsage: "Thanos storage key"
spec:
  name: thanos-secret-config
  secrets:
  - from: ThanosPersistentStoreSecret
    to: thanos_persistent_store_secret