prometheus:
  prometheusSpec:
    disableCompaction: true
    storageSpec:
    thanos:
      image: quay.io/thanos/thanos:v0.28.1
      objectStorageConfig:
        existingSecret:
          name: thanos-objstore-config
          key: ./thanos/thanos.yaml

  thanosService:
    enabled: true